twitter/config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :relationships
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

twitter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

twitter/app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :followed, class_name: "User", foreign_key: :followed_id
    belongs_to :follower, class_name: "User", foreign_key: :follower_id
end

twitter/app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

twitter/app/models/user.rb
class User < ApplicationRecord
    has_many :active_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
    has_many :followeds, through: :active_relationships, source: :followed
    has_many :passive_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
    has_many :followers, through: :passive_relationships, source: :follower
    has_many :tweets
end

twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

twitter/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: %i[ show edit update destroy ]

  # GET /relationships or /relationships.json
  def index
    @relationships = Relationship.all
  end

  # GET /relationships/1 or /relationships/1.json
  def show
  end

  # GET /relationships/new
  def new
    @relationship = Relationship.new
  end

  # GET /relationships/1/edit
  def edit
  end

  # POST /relationships or /relationships.json
  def create
    @relationship = Relationship.new(relationship_params)

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to relationship_url(@relationship), notice: "Relationship was successfully created." }
        format.json { render :show, status: :created, location: @relationship }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relationships/1 or /relationships/1.json
  def update
    respond_to do |format|
      if @relationship.update(relationship_params)
        format.html { redirect_to relationship_url(@relationship), notice: "Relationship was successfully updated." }
        format.json { render :show, status: :ok, location: @relationship }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1 or /relationships/1.json
  def destroy
    @relationship.destroy

    respond_to do |format|
      format.html { redirect_to relationships_url, notice: "Relationship was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relationship
      @relationship = Relationship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def relationship_params
      params.require(:relationship).permit(:follower_id, :followed_id)
    end
end

twitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :content)
    end
end

twitter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username)
    end
end

twitter/app/helpers/application_helper.rb
module ApplicationHelper
end

twitter/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

twitter/app/helpers/tweets_helper.rb
module TweetsHelper
end

twitter/app/helpers/users_helper.rb
module UsersHelper
end

twitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

twitter/app/views/relationships/_form.html.erb
<%= form_with(model: relationship) do |form| %>
  <% if relationship.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
        <% relationship.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :follower_id, style: "display: block" %>
    <%= form.number_field :follower_id %>
  </div>

  <div>
    <%= form.label :followed_id, style: "display: block" %>
    <%= form.number_field :followed_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

twitter/app/views/relationships/_relationship.html.erb
<div id="<%= dom_id relationship %>">
  <p>
    <strong>Follower:</strong>
    <%= relationship.follower_id %>
  </p>

  <p>
    <strong>Followed:</strong>
    <%= relationship.followed_id %>
  </p>

</div>

twitter/app/views/relationships/edit.html.erb
<h1>Editing relationship</h1>

<%= render "form", relationship: @relationship %>

<br>

<div>
  <%= link_to "Show this relationship", @relationship %> |
  <%= link_to "Back to relationships", relationships_path %>
</div>

twitter/app/views/relationships/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Relationships</h1>

<div id="relationships">
  <% @relationships.each do |relationship| %>
    <%= render relationship %>
    <p>
      <%= link_to "Show this relationship", relationship %>
    </p>
  <% end %>
</div>

<%= link_to "New relationship", new_relationship_path %>

twitter/app/views/relationships/new.html.erb
<h1>New relationship</h1>

<%= render "form", relationship: @relationship %>

<br>

<div>
  <%= link_to "Back to relationships", relationships_path %>
</div>

twitter/app/views/relationships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @relationship %>

<div>
  <%= link_to "Edit this relationship", edit_relationship_path(@relationship) %> |
  <%= link_to "Back to relationships", relationships_path %>

  <%= button_to "Destroy this relationship", @relationship, method: :delete %>
</div>

twitter/app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

twitter/app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>User:</strong>
    <%= link_to tweet.user.username, user_path(tweet.user) %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= tweet.content %>
  </p>

</div>

twitter/app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

twitter/app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweets</h1>

<div id="tweets">
  <% @tweets.each do |tweet| %>
    <%= render tweet %>
    <p>
      <%= link_to "Show this tweet", tweet %>
    </p>
  <% end %>
</div>

<%= link_to "New tweet", new_tweet_path %>

twitter/app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

twitter/app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>

twitter/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

twitter/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <h2>
    <strong>Username:</strong>
    <%= user.username %>
  </h2>

  <% if user.followers.count > 0 %>
    <h3>Followers</h3>
    <ul>
    <% user.followers.each do |f| %>
      <li><%= link_to f.username, user_path(f) %></li>
    <% end %>
    </ul>
  <% else %>
  <em><%= user.username %> has no followers :(</em>
  <% end %>

  <% if user.followeds.count > 0 %>
    <h3>Following</h3>
    <ul>
    <% user.followeds.each do |f| %>
      <li><%= link_to f.username, user_path(f) %></li>
    <% end %>
    </ul>
  <% end %>

</div>

twitter/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

twitter/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

twitter/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

twitter/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<h3>Tweets</h3>
<ul>
<% @user.tweets.each do |tweet| %>
  <li><%= link_to tweet.content, tweet_path(tweet) %></li>
<% end %>
</ul>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>